[package]
name = "orbtk_shell_stdweb"
version = "0.3.1-alpha4"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Window shell crate used by OrbTk. Based on stdweb."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["shell", "window", "ui"]
edition = "2018"

[dependencies]
stdweb = "0.4"
derive_more = { version = "0.99", default-features = false, features = ["constructor"] }

# orbtk
orbtk_shell = { path = "../orbtk_shell", version = "0.3.1-alpha4" }
orbtk_render = { path = "../../render/orbtk_render", version = "0.3.1-alpha4" }
orbtk_utils = { path = "../../orbtk_utils", version = "0.3.1-alpha4" }

[features] 
log = []