[package]
name = "orbtk"
version = "0.3.1-alpha4"
authors = [
    "Florian Blasius <flovanpt@posteo.de>",
    "Jeremy Soller <jackpot51@gmail.com>"
]
description = "The Orbital Widget Toolkit"
documentation = "https://docs.rs/orbtk"
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
]
edition = "2018"

[lib]
name = "orbtk"
path = "src/lib.rs"

[profile.dev]
opt-level = 1

[dependencies]
orbtk_proc_macros = { version = "0.3.1-alpha4", path = "crates/orbtk_proc_macros" }

orbtk_render = { version = "0.3.1-alpha4", path = "crates/render/orbtk_render" }
orbtk_shell = { version = "0.3.1-alpha4", path = "crates/shell/orbtk_shell" }
orbtk_theme = { version = "0.3.1-alpha4", path="crates/theme" }
orbtk_theming = { version = "0.3.1-alpha4", path="crates/orbtk_theming" }
orbtk_utils = { version = "0.3.1-alpha4", path = "crates/orbtk_utils" }
orbtk_tree = { version = "0.3.1-alpha4", path="crates/orbtk_tree" }
orbtk_widgets = { version = "0.3.1-alpha4", path="crates/orbtk_widgets", default-features = false }
dces = { git = "https://gitlab.redox-os.org/redox-os/dces-rust.git", branch = "develop" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
orbtk_api = { version = "0.3.1-alpha4", path = "crates/orbtk_api", default-features = false }

[target.wasm32-unknown-unknown.dependencies]
orbtk_api = { version = "0.3.1-alpha4", path = "crates/orbtk_api", default-features = false }

[dev-dependencies]
euc = "0.5.0"
vek = "0.10.2"
serde = "1.0.106"
serde_derive = "1.0.106"

# [target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "redox")))'.dev-dependencies]
# wgpu = "0.5.0"

[features]
default = ["orbtk_api/orbraq", "orbtk_widgets/orbraq"]
debug = ["orbtk_api/debug"]
miniraq = ["orbtk_api/miniraq", "orbtk_widgets/miniraq"]
pathfinder = ["orbtk_shell/pfinder", "orbtk_render/pfinder"]
log = ["orbtk_shell/log"]
light = ["orbtk_theme/light"]
redox = ["orbtk_theme/redox"]
 
[workspace]
members = [
    "crates/orbtk_utils",
    "crates/orbtk_tree",
    "crates/orbtk_proc_macros",
    "crates/orbtk_api",
    "crates/render/orbtk_render",
    "crates/shell/orbtk_shell",
    "crates/shell/orbtk_shell_minifb",
    "crates/shell/orbtk_shell_orbclient",
    "crates/shell/orbtk_shell_stdweb",
    "crates/theme",
    "crates/orbtk_theming",
    "crates/orbtk_widgets",
]
