[package]
name = "orbtk"
version = "0.3.1-alpha2"
authors = [
    "Florian Blasius <flovanpt@posteo.de>",
    "Jeremy Soller <jackpot51@gmail.com>"
]
description = "The Orbital Widget Toolkit"
documentation = "https://docs.rs/orbtk"
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
]
edition = "2018"

[lib]
name = "orbtk"
path = "src/lib.rs"

[profile.dev]
opt-level = 1

[dependencies]
orbtk-api = "0.3.1-alpha2"
orbtk-css-engine = "0.3.1-alpha2"
orbtk-proc-macros = "0.3.1-alpha2"
orbtk-render = "0.3.1-alpha2"
orbtk-shell = "0.3.1-alpha2"
orbtk-theme = "0.3.1-alpha2"
orbtk-utils = "0.3.1-alpha2"
orbtk-tree = "0.3.1-alpha2"
orbtk-widgets = "0.3.1-alpha2"
dces = "0.2"

[dev-dependencies]
euc = "0.4.3"
vek = "0.9.12"
serde = "1.0.104"
serde_derive = "1.0.104"

# [target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "redox")))'.dev-dependencies]
# wgpu = "0.5.0"

[features]
debug = ["orbtk-api/debug"]
 
[workspace]
members = [
    "crates/utils",
    "crates/tree",
    "crates/proc-macros",
    "crates/api",
    "crates/css-engine", 
    "crates/render",
    "crates/shell",
    "crates/theme",
    "crates/widgets",
]
