[package]
name = "orbtk-render"
version = "0.3.1-alpha3"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "2D Render library use by OrbTk."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["2D", "render", "canvas"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.20"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# pathfinder_canvas = "0.5.0"
# pathfinder_geometry = "0.5.1"
# pathfinder_renderer = "0.5.0"
# pathfinder_gl = "0.5.0"
# pathfinder_resources = "0.5.0"
# pathfinder_color = "0.5.0"
raqote = { version = "0.7.14", default-features = false }
rusttype = "0.8.3"
image = "0.23"

[dependencies]
orbtk-utils = { path = "../utils", version = "0.3.1-alpha3" }