[package]
name = "orbtk-api"
version = "0.3.1-alpha3"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "API crate that provides base api and elements for OrbTk like widgets basis."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["ui", "api"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
ron = "0.6"
dirs = "3.0"
dces = "0.3"
orbtk-proc-macros = "0.3.1-alpha3" 
orbtk-utils = "0.3.1-alpha3" 
orbtk-tree = "0.3.1-alpha3" 
orbtk-render = "0.3.1-alpha3" 
orbtk-shell = "0.3.1-alpha3" 
orbtk-theme = "0.3.1-alpha3" 
orbtk-theming = "0.3.1-alpha3" 
derive_more = "0.9"

[target.'cfg(all(not(target_os = "redox")))'.dependencies]
raw-window-handle = "0.3"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.20"

[features]
debug = []
