[package]
name = "orbtk_shell"
version = "0.3.1-alpha4"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Window shell crate used by OrbTk."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["shell", "window", "ui"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.20"

[dependencies]
derive_more = { version = "0.99", default-features = false, features = ["constructor"] }
lazy_static = "1.4.0"
raw-window-handle = "0.3.3"

# orbtk
orbtk_render_raqote = { path = "../../render/orbtk_render_raqote", version = "0.3.1-alpha4", optional = true }
orbtk_utils = { path = "../../orbtk_utils", version = "0.3.1-alpha4" }

[features]
default = ["orbtk_render_raqote"]
log = []