[package]
name = "orbtk_shell_minifb"
version = "0.3.1-alpha4"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = "Window shell crate used by OrbTk."
repository = "https://github.com/redox-os/orbtk"
readme = "README.md"
license = "MIT"
keywords = ["shell", "window", "ui"]
edition = "2018"

[dependencies]
image = { version = "0.23",  default-features = false, features = ["ico"] }
spin_sleep = { version = "1.0" }
minifb = "0.18"
derive_more = { version = "0.99", default-features = false, features = ["constructor"] }
lazy_static = "1.4.0"
raw-window-handle = "0.3.3"

# orbtk
orbtk_shell = { path = "../orbtk_shell", version = "0.3.1-alpha4" }
orbtk_render = { path = "../../render/orbtk_render", version = "0.3.1-alpha4" }
orbtk_utils = { path = "../../orbtk_utils", version = "0.3.1-alpha4" }

[features] 
log = []