name: build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build: 
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
      
    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libwayland-cursor0 libxkbcommon-dev libwayland-dev
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Build widgets example
        run: cargo build --example widgets --verbose
      
  build_redox:
    name: Build on Redox OS
    runs-on: ubuntu-latest
    container: redoxos/redoxer
    
    steps:
      - name: Build widgets example
        run: redoxer build --example widgets --verbose
           
  build_macos:
    name: Build on macOS-latest
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install rust
        run: brew install rust
      - name: Build
        run: cargo build --verbose
      - name: Build widgets example
        run: cargo build --example widgets --verbose

  build_web:
    name: Build on web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install cargo-web
        run: cargo install --force cargo-web
      - name: Build
        run: cargo web build
